name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    services:
      redis:
        image: redis
        ports: [6379/tcp]
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test_cov
    - run: npm run report
      env:
        CI: true
        REDIS_HOST: 127.0.0.1
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
